### PR TITLE
CTA rel tag fix

### LINKED ISSUE #63: Button in the CTA block is sometimes broken in WordPress 5.1
WP 5.1 automatically adds `rel="noopener noreferrer"` to all links that have a `target` attribute. This causes block validation issues.

Reported here: https://wordpress.org/support/topic/whitescreen-an-js-exception-when-editing-site/

WP Trac tickets
https://core.trac.wordpress.org/ticket/46321
https://core.trac.wordpress.org/ticket/46316

### PR DESCRIPTION
**Pull request by mikemcalister**
* Fixes #63

### CODE REVIEW

File: src/blocks/block-cta/deprecated/deprecated.js [hunk 1]
```diff
@@ -380,6 +566,11 @@ export const callToAction_1_4_21_save = props => {
 // Build deprecated list
 
 const deprecated = [
+    // Version 1_5_2
+	{
+		attributes: callToAction_1_5_2_attr,
+        save: callToAction_1_5_2_save,
+    },
```
Comment (mindctrl) [inline src/blocks/block-cta/deprecated/deprecated.js]: @mikemcalister looks like there's some mixed indents here.
